site_name: DataSploit
pages:
- 'Overview': 'index.md'
- 'Setting up the Environment': 'setupGuide.md'
- 'How to Generate Api Keys': 'apiGeneration.md'
- Usage: 'Usage.md'
- Contributors: 'contiributors.md'

